warning

diff --git a/.github/workflows/bootstrap_source.yml b/.github/workflows/bootstrap_source.yml
--- a/.github/workflows/bootstrap_source.yml
+++ b/.github/workflows/bootstrap_source.yml
@@ -70,6 +70,9 @@ jobs:
             boost_url="https://boostorg.jfrog.io/artifactory/main/release/${boost_version}/source"
           elif curl -sfLI "https://archives.boost.io/release/${boost_version}/source/boost_${boost_version//./_}.tar.gz" &> /dev/null; then
             boost_url="https://archives.boost.io/release/${boost_version}/source"
+          else
+            printf '%s\n' "Error: Unable to find a download link for Boost version: $boost_version"
+            exit 1
           fi
 
           mkdir -p assets
